name: Streamlit App Check

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  check_streamlit_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Streamlit App
      run: |
        python -m streamlit run Hello.py &

    - name: Check App Running Status
      run: |
        sleep 10
        echo "Checking Streamlit App Status"
        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8501)
        echo $HTTP_STATUS
        echo $HTTP_STATUS | grep -q 200
